version: 0.2

env:
  variables:
    APACHE_IMAGE_REPO_NAME: "apache"
    PHP_IMAGE_REPO_NAME: "php"
    AWS_DEFAULT_REGION: "ap-southeast-2"
  parameter-store:
    AWS_ACCOUNT_ID: "account_id"
    DB_NAME: "ECSStackDBName"
    DB_USER: "ECSStackDBUSER"
    DB_PASSWORD: "ECSStackDBUSERPasswd"
    DB_HOST: "ECSStackDBEndpoint"
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - APACHE_REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APACHE_IMAGE_REPO_NAME
      - PHP_REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PHP_IMAGE_REPO_NAME
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Codebuild src directory $CODEBUILD_SRC_DIR
      - echo Listing directory structure
      - ls -la
      - echo start building the APACHE Docker image.
      - cd $CODEBUILD_SRC_DIR/apache
      - echo 'Replace PLACEHOLDER in wp-config.php'
      - echo 'Database name is - $DB_NAME'
      - sed -i -e  "s|DB_NAME_PLACEHOLDER|$DB_NAME|" wp-config.php
      - sed -i -e  "s|DB_NAME_PLACEHOLDER|$DB_NAME|" mysql-test.php
      - echo 'Database user is - $DB_USER'
      - sed -i -e  "s|DB_USER_PLACEHOLDER|$DB_USER|" wp-config.php
      - sed -i -e  "s|DB_USER_PLACEHOLDER|$DB_USER|" mysql-test.php
      - echo 'Database password is - $DB_PASSWORD'
      - sed -i -e  "s|DB_PASSWORD_PLACEHOLDER|$DB_PASSWORD|" wp-config.php
      - sed -i -e  "s|DB_PASSWORD_PLACEHOLDER|$DB_PASSWORD|" mysql-test.php
      - echo 'Database Host is - $DB_HOST'
      - sed -i -e  "s|DB_HOST_PLACEHOLDER|$DB_HOST|" wp-config.php
      - sed -i -e  "s|DB_HOST_PLACEHOLDER|$DB_HOST|" mysql-test.php
      - docker build -t $APACHE_IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $APACHE_IMAGE_REPO_NAME:latest $APACHE_REPO_URI:$IMAGE_TAG
      - echo APACHE Docker image build finished.
      - echo start building the PHP Docker image.
      - cd $CODEBUILD_SRC_DIR/php 
      - docker build -t $PHP_IMAGE_REPO_NAME:$IMAGE_TAG . 
      - docker tag $PHP_IMAGE_REPO_NAME:latest $PHP_REPO_URI:$IMAGE_TAG  
      - echo PHP Docker image build finished.
      - echo start building the PHP Docker image.
 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the APACHE Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APACHE_IMAGE_REPO_NAME:latest 
      - printf '[{"name":"apache","imageUri":"%s"}]' $APACHE_REPO_URI:$IMAGE_TAG > apachedefinitions.json
      - cat apachedefinitions.json
      - echo Pushing the PHP Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PHP_IMAGE_REPO_NAME:latest 
      - printf '[{"name":"php","imageUri":"%s"}]' $PHP_REPO_URI:$IMAGE_TAG > phpdefinitions.json
      - cat phpdefinitions.json

artifacts:
    files: 
      - apachedefinitions.json
      - phpdefinitions.json