version: 0.2

env:
  variables:
    APACHE_IMAGE_REPO_NAME: "apache"
    PHP_IMAGE_REPO_NAME: "php"
    AWS_DEFAULT_REGION: "ap-southeast-2"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - APACHE_REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APACHE_IMAGE_REPO_NAME
      - PHP_REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PHP_IMAGE_REPO_NAME
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Codebuild src directory $CODEBUILD_SRC_DIR
      - echo Listing directory structure
      - ls -la
      - echo start building the APACHE Docker image.
      - cat $CODEBUILD_SRC_DIR/apache/Dockerfile > Dockerfile
      - cat Dockerfile
      - docker build -t $APACHE_IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $APACHE_IMAGE_REPO_NAME:latest $APACHE_REPO_URI:$IMAGE_TAG
      - echo APACHE Docker image build finished.
      - echo start building the PHP Docker image.
      - cd $CODEBUILD_SRC_DIR/php/Dockerfile > Dockerfile 
      - cat Dockerfile
      - docker build t $PHP_IMAGE_REPO_NAME:$IMAGE_TAG . 
      - docker tag $PHP_IMAGE_REPO_NAME:latest $PHP_REPO_URI:$IMAGE_TAG  
      - echo PHP Docker image build finished.
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the APACHE Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APACHE_IMAGE_REPO_NAME:latest 
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APACHE_IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"apache","imageUri":"%s"}]' $APACHE_REPO_URI:$IMAGE_TAG > apachedefinitions.json
      - echo Pushing the PHP Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PHP_IMAGE_REPO_NAME:latest 
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PHP_IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"php","imageUri":"%s"}]' $PHP_REPO_URI:$IMAGE_TAG > phpdefinitions.json

artifacts:
    files: 
      - apachedefinitions.json
      - phpdefinitions.json


