version: "3.0"
services:
  webapp:
    build: 
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    container_name: "website"
    depends_on:
      - mysql
      - php
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
  mysql:
    container_name: "database"
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD="${DB_ROOT_PASSWORD}"
      - MYSQL_USER="${DB_USERNAME}"
      - MYSQL_DATABASE="${DB_NAME}"
      - MYSQL_PASSWORD= "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
            - data:/var/lib/mysql
  php:
    container_name: "php"
    build: 
      context: './php'
      args:
       PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
volumes:
    data: