version: "3.0"
services:
  webapp:
    build: ./apache
    container_name: "website"
    depends_on:
      - mysql
      - php
    ports:
      - "80:80"
  mysql:
    container_name: "database"
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=docker
      - MYSQL_DATABASE=mydb
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"
  php:
    container_name: "php"
    build: ./php  
