version: "3.7"
services:
  webapp:
    build: ./apache
    replicas: 1
    depends_on:
      - mysql
      - php
    ports:
      - 80:80
  mysql:
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=mydb
  php:
    build: ./php  
